In [5]:
""" this function takes no of up spin and down spin and index of branch symbol
out is corresponding branch symbol in last letter sequence """
import networkx as nx 
import numpy as np 


def bs(up,down,index):
    ul=[]
    for i in range(up):
        ul.append(1)
     
    dl=[]
    for i in range(down):
        dl.append(0)
        
    k=index-1
    q=int(k/(up-1))
    r=k%(up-1)
    if k==0:
        return ul+dl
    if r==0:
        ul[-(up-1)],dl[q-1]=dl[q-1],ul[-(up-1)]
        return ul + dl 
    else:
        ul[-r],dl[q]=dl[q],ul[-r]
        return ul + dl 
"""for i in range(1,6):
    print(bs(3,2,i))
    """
def rumer(bs):
    rm=[]

    for j in range(1,len(bs)):
        for i in range(0,len(bs)-j):
            if bs[i]==1 and bs[i+j]==0:
                bs[i]="x"
                bs[i+j]='x'
            
                rm.append([i+1,i+j+1])
    
    for k in range(0,len(bs)):
        if bs[k]== 1:
            rm.append([k+1])
    return rm 










def interchange(a):
    a[0],a[1]=a[1],a[0]
    

    
def no_of_two_edge_islands(a,b):
    m=0
    for x in a[:]:
        for y in b:
            if x==y:
                b.remove(x)
                a.remove(x)
                m=m+1
    return  m

def reduced_list(a,b):
    for x in a[:]:
        for y in b:
            if x==y:
                b.remove(x)
                a.remove(x)
    return(a+b)
    

    
    
    
""" Y has to reduced list 
and Z has to cycle in list form """
def sign_of_island(Y,Z):
    p=0    
    for x in Y:
        for y in Z:
            if x==interchange(y):
                p=p+1
    return (-1)**(p%2)

import networkx as nx 

""" find the cycles in given graph """
def find_cycles(x):
    
    g=nx.Graph()
    
    g.add_edges_from(x)
    l=nx.algorithms.cycles.find_cycle(g)
    m=[list(ele) for ele in l]
    return m 


""" applies the permutation operator on rumer basis vector """

def permute(i,j,b):
    a=b[:]
    k=0
    l=0
    m=0
    n=0
    for x in range(len(a)) :
        for y in range(len(a[x])):
            if a[x][y]==i:
                k,l=x,y
                
    for p in range(len(a)) :
        for q in range(len(a[p])) :
            if a[p][q]==j :
                m,n=p,q
    
    a[k][l],a[m][n]=a[m][n],a[k][l]
    return a 
""" take two rumer vectors 
"""

def rumer_dot(a,b,n):
    island_2=no_of_two_edge_islands(a,b)
    red_list=reduced_list(a,b)
    cycles=list_of_cycles(red_list)
    island_3=len(cycles)
    islands=island_2+island_3
    finalsign=1
    for i in range(len(cycles)):
        i_sign=sign_of_island(red_list,cycles[i])
        finalsign=finalsign*i_sign
    rirj=(2**(islands-(n/2)))*finalsign
    return rirj
    
    
def si_dot_sj_in_rumer(i,j,n):
    a=rumer(bs(int(n/2),int(n/2),i))
    b=rumer(bs(int(n/2),int(n/2),j))
    print(a,b)
    rirj=rumer_dot(a,b,n)
    p_rirj=rumer_dot(a,permute(i,j,b),n)
    
    print(rirj,p_rirj)
    return .5*p_rirj-(.25*rirj)
  


def f(n,s):
    if n==2 and s==0:
        return 1
    if n==2 and s==1:
        return 1
    
    if s>(n/2):
        return 0
    if s==(n/2):
        return 1
    if 0<=s<(n/2):
        return f(n-1,s+0.5)+f(n-1,s-.5)
    if s<0:
        return 0

def branch(n,s,i):
    k=[]
    if i<=f(n-1,s+.5):
        if f(n-1,s+.5)>1:
            k.append(0)
            return branch(n-1,s+.5,i)+[0]
        if f(n-1,s+.5)==1:
            k.append(0)
            m=[]
            for p in range(n-1):
                m.append(1)
            return m+k
    if i> f(n-1,s+.5):
        k.append(1)
        return branch(n-1,s-.5,i-f(n-1,s+.5))+[1]

In [3]:

import networkx as nx 


""" Y has to reduced list 
and Z has to cycle in list form """
def sign_of_island(Y,Z):
    p=0
    for x in a:
        for y in b:
            
            if x==y:
                p=p+1
    return -1**((len(a)-p)%2)









""" it will take reduced list and produce the list in which each element is a cycle """     
def list_of_cycles(red_list):
    g=nx.Graph()
    g.add_edges_from(red_list)
    l=nx.algorithms.cycles.cycle_basis(g)
    final_list=[]
    for i in range(len(l)):
        final_list.append(form_basis_list_cycles(l[i]))
        
    return final_list


def f(n,s):
    if n==2 and s==0:
        return 1
    if n==2 and s==1:
        return 1
    
    if s>(n/2):
        return 0
    if s==(n/2):
        return 1
    if 0<=s<(n/2):
        return f(n-1,s+0.5)+f(n-1,s-.5)
    if s<0:
        return 0
def branch(n,s,i):
    k=[]
    if i<=f(n-1,s+.5):
        if f(n-1,s+.5)>1:
            k.append(0)
            return branch(n-1,s+.5,i)+[0]
        if f(n-1,s+.5)==1:
            k.append(0)
            m=[]
            for p in range(n-1):
                m.append(1)
            return m+k
    if i> f(n-1,s+.5):
        k.append(1)
        return branch(n-1,s-.5,i-f(n-1,s+.5))+[1]
    

def ridotrj(a,b,n):
    island2=no_of_two_edge_islands(a,b)
    
    reducedlist=reduced_list(a,b)
    list_of_other_cycles=list_of_cycles(reducedlist)
    island3=len(list_of_other_cycles)
    
    totalislands=island2+island3
    
    finalsign=1
    
    for i in range(len(list_of_other_cycles)):
        island_sign=sign_of_island(reducedlist,list_of_other_cycles[i])
        finalsign=finalsign*island_sign
        
    rirj=(2**(-n/2))*(2**( totalislands))*finalsign
    
    return rirj
""" this program takes n== no of spin 
  s and index """   
def ru(n,s,i):
    return rumer(branch(n,s,i))

""" this is for matrix element k l for pair ij given n and s """
def xyzsisj(i,j,k,l,n,s):
    ri=ru(n,s,i)
    rj=ru(n,s,j)
    return .5*ridotrj(ri,permute(k,l,rj),n)- .25*ridotrj(ri,rj,n) 


""" this give i andj are particle number """
def mat_sisj(i,j,n,s):
    arr = np.empty((f(n,s),f(n,s)), dtype=object)
    for i in range(0,f(n,s)):
        for j in range(0,(f(n,s))):
            if i==j:
            #print(1)
                arr[i,j]=1
            if i!=j:
                #print(xyzsisj(i,j,1,2, 10,0))
                arr[i,j]=xyzsisj(i+1,j+1,i,j, n,s)
    return arr
    

    

In [7]:
import numpy as np
arr = np.empty((42,42), dtype=object)
for i in range(0,42):
    for j in range(0,42):
        if i==j:
            #print(1)
            arr[i,j]=1
        if i!=j:
            #print(xyzsisj(i,j,1,2, 10,0))
            arr[i,j]=xyzsisj(i+1,j+1,1,2, 10,0)
print(arr)

[[1 0.09375 0.03125 ... 0.03125 0.046875 0.09375]
 [0.09375 1 0.09375 ... 0.09375 0.015625 0.03125]
 [0.03125 0.09375 1 ... 0.03125 0.03125 0.09375]
 ...
 [0.03125 0.09375 0.03125 ... 1 0.109375 0.109375]
 [0.046875 0.015625 0.03125 ... 0.109375 1 0.234375]
 [0.09375 0.03125 0.09375 ... 0.109375 0.234375 1]]


In [6]:
""" this give i andj are particle number """
def mat_sisj(k,l,n,s):
    arr = np.empty((f(n,s),f(n,s)), dtype=object)
    for i in range(0,f(n,s)):
        for j in range(0,(f(n,s))):
            if i==j:
            #print(1)
                arr[i,j]=1
            if i!=j:
                #print(xyzsisj(i,j,1,2, 10,0))
                arr[i,j]=xyzsisj(i+1,j+1,k,l, n,s)
    return arr
    
    
print(mat_sisj(1,2,10,0)) 

[[1 0.09375 0.03125 ... 0.03125 0.046875 0.09375]
 [0.09375 1 0.09375 ... 0.09375 0.015625 0.03125]
 [0.03125 0.09375 1 ... 0.03125 0.03125 0.09375]
 ...
 [0.03125 0.09375 0.03125 ... 1 0.109375 0.109375]
 [0.046875 0.015625 0.03125 ... 0.109375 1 0.234375]
 [0.09375 0.03125 0.09375 ... 0.109375 0.234375 1]]
